# Generated by Django 5.2.16 on 2026-07-16 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='E-mail do Destinatário')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Corpo do E-mail')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('type', models.CharField(choices=[('INVITATION', 'Convite'), ('REMINDER', 'Lembrete'), ('POST_EVENT', 'Pós-Evento')], default='INVITATION', max_length=20, verbose_name='Tipo')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.evento', verbose_name='Evento')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mail',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Aberto em')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Clicado em')),
                ('email_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='communications.emaillog')),
            ],
            options={
                'verbose_name': 'Rastreamento de E-mail',
                'verbose_name_plural': 'Rastreamentos de E-mail',
            },
        ),
    ]
