# Generated by Django 5.2.16 on 2026-07-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='type',
            field=models.CharField(choices=[('INVITATION', 'Convite'), ('REMINDER', 'Lembrete'), ('POST_EVENT', 'Pós-Evento'), ('ENROLLMENT_CONFIRMATION', 'Confirmação de Inscrição')], default='INVITATION', max_length=30, verbose_name='Tipo'),
        ),
    ]
