# Generated by Django 5.2.16 on 2026-07-16 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Início')),
                ('end_time', models.TimeField(verbose_name='Término')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Local')),
                ('is_online', models.BooleanField(default=False, verbose_name='Online?')),
                ('online_platform', models.CharField(blank=True, max_length=100, verbose_name='Plataforma Online')),
                ('online_link', models.URLField(blank=True, verbose_name='Link Online')),
                ('benegnadores', models.ManyToManyField(blank=True, to='people.benegnador', verbose_name='Benegnadores')),
                ('benegnados', models.ManyToManyField(blank=True, to='accounts.benegnado', verbose_name='Participantes (Benegnados)')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventtype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
    ]
