# Generated by Django 5.2.16 on 2026-07-16 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='benegnados',
        ),
        migrations.AddField(
            model_name='evento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='evento',
            name='is_public_enrollment_open',
            field=models.BooleanField(default=True, verbose_name='Inscrição Pública Aberta?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vagas Máximas'),
        ),
        migrations.AddField(
            model_name='evento',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug Público'),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmada'), ('CANCELLED', 'Cancelada')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('origin', models.CharField(choices=[('SELF_ENROLLED', 'Auto-Inscrito'), ('ADMIN_ADDED', 'Adicionado pelo Admin')], default='SELF_ENROLLED', max_length=20, verbose_name='Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('benegnado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='accounts.benegnado', verbose_name='Participante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='events.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('evento', 'benegnado')},
            },
        ),
    ]
