version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_economia_natural
    restart: unless-stopped
    environment:
      POSTGRES_DB: economia_natural
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: web_economia_natural
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  sqlite_data:
