# Generated by Django 5.2.16 on 2026-07-16 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benegnado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone/WhatsApp')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='Empresa')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benegnado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benegnado',
                'verbose_name_plural': 'Benegnados',
            },
        ),
    ]
