# Generated by Django 5.2.16 on 2026-07-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benegnado',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Forcar troca de senha?'),
        ),
    ]
