# Generated by Django 5.2.16 on 2026-07-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_benegnado_must_change_password'),
        ('accounts', '0002_create_admin'),
    ]

    operations = [
    ]
