# Generated by Django 5.2.16 on 2026-07-16 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('weight', models.DecimalField(decimal_places=2, default=0.25, max_digits=4, verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Dimensão de Impacto',
                'verbose_name_plural': 'Dimensões de Impacto',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImpactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Formulário')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_forms', to='events.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Formulário de Impacto',
                'verbose_name_plural': 'Formulários de Impacto',
            },
        ),
        migrations.CreateModel(
            name='ImpactQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto da Pergunta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_open', models.BooleanField(default=False, verbose_name='É aberta (discursiva)?')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='impact_forms.impactdimension', verbose_name='Dimensão')),
            ],
            options={
                'verbose_name': 'Pergunta de Impacto',
                'verbose_name_plural': 'Perguntas de Impacto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ImpactResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('benegnado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_responses', to='accounts.benegnado', verbose_name='Benegnado')),
                ('impact_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='impact_forms.impactform', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Resposta de Impacto',
                'verbose_name_plural': 'Respostas de Impacto',
                'unique_together': {('impact_form', 'benegnado')},
            },
        ),
        migrations.CreateModel(
            name='ImpactAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Valor Likert (1-5)')),
                ('text_answer', models.TextField(blank=True, verbose_name='Resposta Discursiva')),
                ('impact_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impact_forms.impactquestion', verbose_name='Pergunta')),
                ('impact_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='impact_forms.impactresponse', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Resposta Individual',
                'verbose_name_plural': 'Respostas Individuais',
            },
        ),
    ]
