# Generated by Django 5.2.16 on 2026-07-16 01:08

from django.db import migrations

def populate_default_questions(apps, schema_editor):
    ImpactDimension = apps.get_model('impact_forms', 'ImpactDimension')
    ImpactQuestion = apps.get_model('impact_forms', 'ImpactQuestion')

    # Dimensions
    dim_d1, _ = ImpactDimension.objects.get_or_create(
        name="Consciência e Identidade",
        defaults={'code': 'D1', 'weight': 0.25}
    )
    dim_d2, _ = ImpactDimension.objects.get_or_create(
        name="Coerência e Atitudes",
        defaults={'code': 'D2', 'weight': 0.30}
    )
    dim_d3, _ = ImpactDimension.objects.get_or_create(
        name="Relações",
        defaults={'code': 'D3', 'weight': 0.25}
    )
    dim_d4, _ = ImpactDimension.objects.get_or_create(
        name="Contribuição",
        defaults={'code': 'D4', 'weight': 0.20}
    )

    questions_data = [
        # D1
        (dim_d1, 'Sinto que minhas decisões estão mais alinhadas com meu propósito.', False),
        (dim_d1, 'Compreendo melhor meus padrões emocionais.', False),
        (dim_d1, 'Evito culpar fatores externos quando não alcanço os resultados esperados.', False),
        (dim_d1, 'A Escola de Oportunidade marcou uma virada importante na minha trajetória.', False),
        
        # D2
        (dim_d2, 'Passei a tomar decisões mais alinhadas aos meus valores.', False),
        (dim_d2, 'Incorporei novos hábitos positivos após a EO.', False),
        (dim_d2, 'Encaro desafios com mais maturidade e consciência.', False),
        (dim_d2, 'Sinto maior coerência entre o que penso e o que faço.', False),
        
        # D3
        (dim_d3, 'Tenho conseguido levar em consideração opiniões diferentes das minhas.', False),
        (dim_d3, 'Me comunico com mais clareza e respeito.', False),
        (dim_d3, 'Lido melhor com conflitos do que antes.', False),
        (dim_d3, 'Pessoas próximas perceberam mudanças positivas em mim.', False),
        
        # D4
        (dim_d4, 'Passei a apoiar mais o desenvolvimento de outras pessoas.', False),
        (dim_d4, 'Compartilho os aprendizados da EO no meu cotidiano.', False),
        (dim_d4, 'Estou mais envolvido em iniciativas coletivas (no meu bairro, igreja, na minha comunidade de amigos, etc.).', False),
        (dim_d4, 'Acredito que minha mudança influencia outras pessoas.', False),
        
        # Abertas (Sem dimensão vinculada obrigatoriamente para pontuação, mas pode vincular a uma delas ou deixar dimensão, no schema dimension é ForeignKey, então vinculamos a D4 ou D1. A view sabe que é aberta)
        (dim_d4, 'Você poderia nos dizer qual mudança mais significativa você percebe em si mesmo desde o início da EO?', True),
        (dim_d4, 'E onde essa mudança aparece na prática no seu cotidiano? Poderia nos dar alguns exemplos?', True),
        (dim_d4, 'E para finalizar, como você acredita que estaria hoje se não tivesse participado da EO?', True),
    ]

    for order, (dimension, text, is_open) in enumerate(questions_data, start=1):
        ImpactQuestion.objects.get_or_create(
            text=text,
            defaults={
                'dimension': dimension,
                'order': order,
                'is_open': is_open
            }
        )

def reverse_populate(apps, schema_editor):
    ImpactDimension = apps.get_model('impact_forms', 'ImpactDimension')
    ImpactQuestion = apps.get_model('impact_forms', 'ImpactQuestion')
    ImpactQuestion.objects.all().delete()
    ImpactDimension.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('impact_forms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_default_questions, reverse_populate),
    ]
