# Generated by Django 5.2.16 on 2026-07-16 01:08

from django.db import migrations

def populate_default_questions(apps, schema_editor):
    ImpactDimension = apps.get_model('impact_forms', 'ImpactDimension')
    ImpactQuestion = apps.get_model('impact_forms', 'ImpactQuestion')

    # Dimensions
    dim_conscientizacao, _ = ImpactDimension.objects.get_or_create(
        name="Conscientizacao",
        defaults={'code': 'CONS', 'weight': 0.33}
    )
    dim_educacao, _ = ImpactDimension.objects.get_or_create(
        name="Educacao",
        defaults={'code': 'EDUC', 'weight': 0.33}
    )
    dim_acao, _ = ImpactDimension.objects.get_or_create(
        name="Acao",
        defaults={'code': 'ACAO', 'weight': 0.34}
    )

    questions_data = [
        # Conscientizacao
        (dim_conscientizacao, 'Em que medida este evento aumentou sua compreensao sobre as praticas de sustentabilidade?'),
        (dim_conscientizacao, 'Como voce avalia a clareza das informacoes apresentadas durante o evento?'),
        (dim_conscientizacao, 'Qual foi o impacto do evento na sua percepcao sobre a importancia da economia circular?'),
        
        # Educacao
        (dim_educacao, 'O quao uteis foram os materiais educativos disponibilizados no evento?'),
        (dim_educacao, 'Em que grau os palestrantes/facilitadores demonstraram dominio sobre os temas abordados?'),
        (dim_educacao, 'Como o evento contribuiu para o seu desenvolvimento profissional na area de ESG?'),
        
        # Acao
        (dim_acao, 'O evento motivou voce a implementar praticas mais sustentaveis em sua organizacao/dia a dia?'),
        (dim_acao, 'Qual a probabilidade de voce adotar uma nova pratica de sustentabilidade no proximo mes devido a este evento?'),
        (dim_acao, 'O quao preparado(a) voce se sente para compartilhar os conhecimentos adquiridos com outras pessoas?'),
        (dim_acao, 'Como voce avalia as oportunidades de networking oferecidas para futuras colaboracoes em sustentabilidade?'),
    ]

    for order, (dimension, text) in enumerate(questions_data, start=1):
        ImpactQuestion.objects.get_or_create(
            text=text,
            defaults={
                'dimension': dimension,
                'order': order
            }
        )

def reverse_populate(apps, schema_editor):
    ImpactDimension = apps.get_model('impact_forms', 'ImpactDimension')
    ImpactQuestion = apps.get_model('impact_forms', 'ImpactQuestion')
    ImpactQuestion.objects.all().delete()
    ImpactDimension.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('impact_forms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_default_questions, reverse_populate),
    ]
