# Generated by Django 5.2.16 on 2026-07-20

from django.db import migrations

def force_repopulate(apps, schema_editor):
    ImpactDimension = apps.get_model('impact_forms', 'ImpactDimension')
    ImpactQuestion = apps.get_model('impact_forms', 'ImpactQuestion')
    ImpactResponse = apps.get_model('impact_forms', 'ImpactResponse')
    
    # Apaga tudo para evitar duplicatas e reseta (CUIDADO: isso apaga respostas, mas como estamos em deploy inicial na VPS, é o ideal)
    ImpactResponse.objects.all().delete()
    ImpactQuestion.objects.all().delete()
    ImpactDimension.objects.all().delete()

    # Importa a função do 0002 e roda ela
    import importlib
    mod = importlib.import_module('impact_forms.migrations.0002_populate_default_questions')
    mod.populate_default_questions(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('impact_forms', '0002_populate_default_questions'),
    ]

    operations = [
        migrations.RunPython(force_repopulate, migrations.RunPython.noop),
    ]
