# Generated by Django 5.2.16 on 2026-07-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benegnador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Benegnador',
                'verbose_name_plural': 'Benegnadores',
                'ordering': ['name'],
            },
        ),
    ]
