# Generated by Django 5.2.16 on 2026-07-16 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Vídeo'), ('ARTICLE', 'Artigo')], default='PDF', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='contents/', verbose_name='Arquivo')),
                ('external_link', models.URLField(blank=True, verbose_name='Link Externo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='events.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Conteúdo',
                'verbose_name_plural': 'Conteúdos',
                'ordering': ['title'],
            },
        ),
    ]
